[package]
name = "stackbt_macros"
version = "0.1.0"
authors = ["eaglgenes101 <eaglgenes101@gmail.com>"]
readme = "../README.md"
license = "MIT/Apache-2.0"
description = "Macros for StackBT"
repository = "https://github.com/eaglgenes101/stackbt"